"""empty message

Revision ID: 1685b74d3aea
Revises: 3729bfa76dda
Create Date: 2016-05-31 11:13:54.531517

"""

# revision identifiers, used by Alembic.
revision = '1685b74d3aea'
down_revision = '3729bfa76dda'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('COMMIT')
    op.execute("ALTER TYPE classifier_grid_params_statuses ADD VALUE 'Error'")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
