"""empty message

Revision ID: 268e13258471
Revises: 41d161df6137
Create Date: 2016-10-23 18:22:48.200311

"""

# revision identifiers, used by Alembic.
revision = '268e13258471'
down_revision = '41d161df6137'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    pass
    # mistake migration
    ### commands auto generated by Alembic - please adjust! ###
    ### end Alembic commands ###


def downgrade():
    pass
    # mistake migration
    ### commands auto generated by Alembic - please adjust! ###
    ### end Alembic commands ###
