"""empty message

Revision ID: 2bb2f49a8c2a
Revises: 1bf1ced592f8
Create Date: 2016-08-31 15:17:27.382259

"""

# revision identifiers, used by Alembic.
revision = '2bb2f49a8c2a'
down_revision = '1bf1ced592f8'

from alembic import op
import sqlalchemy as sa
from api.base.models import JSONType

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('model_parts_size', JSONType(),
                                     nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model', 'model_parts_size')
    ### end Alembic commands ###
