"""Add_env_type

Revision ID: 3729bfa76dda
Revises: 394da0f7e9f2
Create Date: 2016-04-05 16:57:29.582627

"""

# revision identifiers, used by Alembic.
revision = '3729bfa76dda'
down_revision = '394da0f7e9f2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('COMMIT')
    op.execute("ALTER TYPE server_types ADD VALUE 'Analytics'")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
