"""empty message

Revision ID: 37ed0c2cca94
Revises: 2bb2f49a8c2a
Create Date: 2016-10-21 12:05:37.497781

"""

# revision identifiers, used by Alembic.
revision = '37ed0c2cca94'
down_revision = '2bb2f49a8c2a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from api.base.models import JSONType


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periodic_task_scenarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('updated_on', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scenarios', JSONType(), nullable=True),
    sa.Column('interval', JSONType(), nullable=True),
    sa.Column('crontab', JSONType(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_periodic_task_scenarios_updated_by_id', 'periodic_task_scenarios', ['updated_by_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_periodic_task_scenarios_updated_by_id', 'periodic_task_scenarios')
    op.drop_table('periodic_task_scenarios')
    ### end Alembic commands ###
