"""empty message

Revision ID: 394da0f7e9f2
Revises: f1eadcc236d
Create Date: 2016-03-18 14:48:24.101815

"""

# revision identifiers, used by Alembic.
revision = '394da0f7e9f2'
down_revision = 'f1eadcc236d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('logs_url', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'logs_url')
    ### end Alembic commands ###
