"""empty message

Revision ID: 395aff1cdc53
Revises: bc09e77c7d0
Create Date: 2016-10-23 15:17:21.896287

"""

# revision identifiers, used by Alembic.
revision = '395aff1cdc53'
down_revision = 'bc09e77c7d0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'periodic_task_scenarios', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'periodic_task_scenarios')
    ### end Alembic commands ###
