"""empty message

Revision ID: 41d161df6137
Revises: 395aff1cdc53
Create Date: 2016-10-23 18:16:08.488599

"""

# revision identifiers, used by Alembic.
revision = '41d161df6137'
down_revision = '59bbbbdfade9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'periodic_task_scenarios', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'periodic_task_scenarios')
    ### end Alembic commands ###
