"""empty message

Revision ID: 41d161df6137
Revises: 395aff1cdc53
Create Date: 2016-10-23 18:16:08.488599

"""

# revision identifiers, used by Alembic.
revision = '41d161df6137'
down_revision = '395aff1cdc53'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('periodic_task_scenarios', sa.Column('periodictask_id', sa.Integer(), nullable=True))
    op.alter_column('periodic_task_scenarios', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('periodic_task_scenarios', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('periodic_task_scenarios', 'periodictask_id')
    ### end Alembic commands ###
