"""empty message

Revision ID: 46a8254d3b5e
Revises: 1685b74d3aea
Create Date: 2016-06-28 12:59:36.830087

"""

# revision identifiers, used by Alembic.
revision = '46a8254d3b5e'
down_revision = '1685b74d3aea'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from api.base.models import JSONType
from api.servers.scripts import set_server_ids


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('servers_ids', JSONType(), nullable=True))
    op.add_column('xml_import_handler', sa.Column('servers_ids', JSONType(),
                                                  nullable=True))
    set_server_ids()
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('xml_import_handler', 'servers_ids')
    op.drop_column('model', 'servers_ids')
    ### end Alembic commands ###
