"""Add clusters

Revision ID: 4b8f9005cb69
Revises: 2fa7c91f4778
Create Date: 2014-04-26 09:25:13.767545

"""

# revision identifiers, used by Alembic.
revision = '4b8f9005cb69'
down_revision = '2fa7c91f4778'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.func.now(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.func.now(), nullable=True),
    sa.Column('jobflow_id', sa.String(length=200), nullable=False),
    sa.Column('master_node_dns', sa.String(length=200), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('New', 'Starting', 'Running', 'Waiting', 'Error', 'Terminated', name='cluster_statuses'), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jobflow_id')
    )
    op.add_column(u'data_set', sa.Column('cluster_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'data_set', 'cluster_id')
    op.drop_table('cluster')
    ### end Alembic commands ###
    ENUM(name='cluster_statuses').drop(op.get_bind(), checkfirst=False)
