"""empty message

Revision ID: 59bbbbdfade9
Revises: None
Create Date: 2016-10-18 12:40:03.342932

"""

# revision identifiers, used by Alembic.
revision = '59bbbbdfade9'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###

    op.add_column('periodic_task_scenarios', sa.Column('crontab', sa.JSON(), nullable=True))
    op.add_column('periodic_task_scenarios', sa.Column('interval', sa.JSON(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('periodic_task_scenarios', 'interval')
    op.drop_column('periodic_task_scenarios', 'crontab')

    ### end Alembic commands ###
