"""empty message

Revision ID: 88222ec90e4
Revises: 3e454e1e3715
Create Date: 2015-10-27 10:45:13.074517

"""

# revision identifiers, used by Alembic.
revision = '88222ec90e4'
down_revision = '3e454e1e3715'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('COMMIT')
    op.execute("CREATE TYPE xml_script_types AS ENUM('python_code', 'python_file')")
    op.add_column('xml_script', sa.Column('type', sa.Enum('python_code', 'python_file', name='xml_script_types'), server_default='python_code'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('xml_script', 'type')
    op.execute('DROP TYPE xml_script_types')
    ### end Alembic commands ###
