"""empty message

Revision ID: aaf5c4cf6b5
Revises: 3e454e1e3715
Create Date: 2015-11-13 10:32:31.477532

"""

# revision identifiers, used by Alembic.
revision = 'aaf5c4cf6b5'
down_revision = '3e454e1e3715'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('COMMIT')
    op.execute("CREATE TYPE server_types AS ENUM('Production', 'Staging', 'Development')")
    op.add_column('server', sa.Column('type', sa.Enum('Production', 'Staging', 'Development', name='server_types'), server_default='Development'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'type')
    op.execute('DROP TYPE server_types')
    ### end Alembic commands ###
