"""empty message

Revision ID: bc09e77c7d0
Revises: 59bbbbdfade9
Create Date: 2016-10-18 15:33:57.546857

"""

# revision identifiers, used by Alembic.
revision = 'bc09e77c7d0'
down_revision = '59bbbbdfade9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('periodic_task_scenarios', sa.Column('descriptions', sa.String(length=254), nullable=True))
    op.add_column('periodic_task_scenarios', sa.Column('error', sa.String(length=254), nullable=True))
    op.add_column('periodic_task_scenarios', sa.Column('no_changes', sa.Boolean(), nullable=True))
    op.add_column('periodic_task_scenarios', sa.Column('status', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('periodic_task_scenarios', 'status')
    op.drop_column('periodic_task_scenarios', 'no_changes')
    op.drop_column('periodic_task_scenarios', 'error')
    op.drop_column('periodic_task_scenarios', 'descriptions')
    ### end Alembic commands ###
