module.exports =
  cdn: [
      external:
        "https://cdnjs.cloudflare.com/ajax/libs/lodash.js/2.4.1/lodash.min.js"
      local:
        "bower_components/lodash/dist/lodash.js"
    ,
      external:
        "https://cdnjs.cloudflare.com/ajax/libs/jquery/1.8.3/jquery.min.js"
      local:
        "bower_components/jquery/jquery.js"
    ,
      external:
        "https://maxcdn.bootstrapcdn.com/bootstrap/2.3.0/js/bootstrap.min.js"
      local:
        "bootstrap js here"
    ,
      external:
        "https://cdnjs.cloudflare.com/ajax/libs/x-editable/1.4.4/bootstrap-editable/js/bootstrap-editable.min.js"
      local:
        "x-editable here"
    ,
      external:
        "https://cdnjs.cloudflare.com/ajax/libs/d3/3.4.11/d3.min.js"
      local:
        "bower_components/d3/d3.js"
    ,
      external:
        "https://ajax.googleapis.com/ajax/libs/angularjs/1.2.20/angular.js"
      local:
        "bower_components/angular/angular.js"
    ,
      external:
        "https://ajax.googleapis.com/ajax/libs/angularjs/1.2.20/angular-route.min.js"
      local:
        "bower_components/angular-route/angular-route.js"
    ,
      external:
        "https://ajax.googleapis.com/ajax/libs/angularjs/1.2.20/angular-resource.min.js"
      local:
        "bower_components/angular-resource/angular-resource.js"
    ,
      external:
        "https://ajax.googleapis.com/ajax/libs/angularjs/1.2.20/angular-cookies.min.js"
      local:
        "bower_components/angular-cookies/angular-cookies.js"
    ,
      external:
        "https://ajax.googleapis.com/ajax/libs/angularjs/1.2.20/angular-sanitize.min.js"
      local:
        "bower_components/angular-sanitize/angular-sanitize.js"
  ]
  bundled: [
    "vendor/scripts/console-helper.js"
    "bower_components/select2/select2.js"
    "bower_components/angular-bootstrap/ui-bootstrap-tpls-0.10.0.js"
    "bower_components/angular-ui-select2/src/select2.js"
    "bower_components/moment/moment.js"
    "bower_components/codemirror/lib/codemirror.js"
    "bower_components/codemirror/mode/sql/sql.js"
    "bower_components/codemirror/mode/xml/xml.js"
    "bower_components/codemirror/mode/python/python.js"
    "bower_components/codemirror/mode/javascript/javascript.js"
    "bower_components/angular-ui-codemirror/ui-codemirror.js"
  ]