"""empty message

Revision ID: 1ca38012a07d
Revises: 8e2d9d09c0a
Create Date: 2014-08-18 17:08:33.169823

"""

# revision identifiers, used by Alembic.
revision = '1ca38012a07d'
down_revision = '8e2d9d09c0a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('predict_model_weight', 'label',
               existing_type=sa.Boolean(),
               type_=sa.String(length=200),
               nullable=True)
    op.alter_column('predict_result_probability', 'label',
               existing_type=sa.Boolean(),
               type_=sa.String(length=200),
               nullable=True)
   
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
