"""adding_predict_to_xml_import_handlers

Revision ID: 2b86c9ec2345
Revises: 323f586eb1f5
Create Date: 2014-07-10 18:37:41.819760

"""

# revision identifiers, used by Alembic.
revision = '2b86c9ec2345'
down_revision = '323f586eb1f5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predict_model_positive_label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=True),
    sa.Column('script', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predict_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=True),
    sa.Column('script', sa.Text(), nullable=True),
    sa.Column('positive_label_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['positive_label_id'], ['predict_model_positive_label.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predict_result_probability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('script', sa.Text(), nullable=True),
    sa.Column('label', sa.Boolean(), nullable=True),
    sa.Column('predict_model_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['predict_model_id'], ['predict_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predict_result_label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('script', sa.Text(), nullable=True),
    sa.Column('predict_model_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['predict_model_id'], ['predict_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predict_model_weight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=True),
    sa.Column('script', sa.Text(), nullable=True),
    sa.Column('label', sa.Boolean(), nullable=True),
    sa.Column('predict_model_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['predict_model_id'], ['predict_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predict',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.Column('probability_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['label_id'], ['predict_result_label.id'], ),
    sa.ForeignKeyConstraint(['probability_id'], ['predict_result_probability.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predict_models_table',
    sa.Column('predict_model_id', sa.Integer(), nullable=True),
    sa.Column('predict_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['predict_id'], ['predict.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['predict_model_id'], ['predict_model.id'], onupdate='CASCADE', ondelete='CASCADE')
    )
    op.add_column(u'xml_import_handler', sa.Column('predict_id', sa.Integer(), nullable=True))

def downgrade():
    op.drop_column(u'xml_import_handler', 'predict_id')
    op.drop_table('predict_models_table')
    op.drop_table('predict')
    op.drop_table('predict_model_weight')
    op.drop_table('predict_result_label')
    op.drop_table('predict_result_probability')
    op.drop_table('predict_model')
    op.drop_table('predict_model_positive_label')
