"""empty message

Revision ID: 38526ac28bcf
Revises: 2c09c89728ac
Create Date: 2014-12-15 14:45:23.240620

"""

# revision identifiers, used by Alembic.
revision = '38526ac28bcf'
down_revision = '2c09c89728ac'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('xml_field', sa.Column('key_path', sa.String(length=200), nullable=True))
    op.add_column('xml_field', sa.Column('value_path', sa.String(length=200), nullable=True))



def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('xml_field', 'value_path')
    op.drop_column('xml_field', 'key_path')
    ### end Alembic commands ###
