"""empty message

Revision ID: 403c519d5ffc
Revises: 2f078385306e
Create Date: 2014-09-20 16:09:14.248391

"""

# revision identifiers, used by Alembic.
revision = '403c519d5ffc'
down_revision = '2f078385306e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weight', sa.Column('value2', sa.Float(), nullable=True))  
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weight', 'value2')
    ### end Alembic commands ###
