"""empty message

Revision ID: 451a64d06984
Revises: 57721a4a79d5
Create Date: 2016-02-09 16:11:02.294860

"""

# revision identifiers, used by Alembic.
revision = '451a64d06984'
down_revision = '57721a4a79d5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('COMMIT')
    op.execute("ALTER TYPE pretrained_transformer_types ADD value 'Word2Vec';")
    op.execute("ALTER TYPE pretrained_transformer_types ADD value 'Doc2Vec';")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
