"""classifiers

Revision ID: 54d3f2d13dc4
Revises: 1673608b3b2d
Create Date: 2015-08-11 12:17:55.442614

"""

# revision identifiers, used by Alembic.
revision = '54d3f2d13dc4'
down_revision = '1673608b3b2d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('COMMIT')
    op.execute("ALTER TYPE scaler_types ADD value 'NoScaler';")
    op.execute("ALTER TYPE pretrained_transformer_types ADD value 'Ntile';")
    op.execute("ALTER TYPE classifier_types ADD value "
               "'decision tree classifier';")
    op.execute("ALTER TYPE classifier_types ADD value "
               "'extra trees classifier';")
    op.execute("ALTER TYPE classifier_types ADD value "
               "'random forest classifier';")

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
