"""empty message

Revision ID: 57721a4a79d5
Revises: aaf5c4cf6b5
Create Date: 2015-12-18 15:21:59.720964

"""

# revision identifiers, used by Alembic.
revision = '57721a4a79d5'
down_revision = 'aaf5c4cf6b5'

from alembic import op
import sqlalchemy as sa
from api.servers.models import Server


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    servers = Server.query.filter(Server.name.like('%Production%')).all()
    for server in servers:
        server.type = Server.PRODUCTION
        server.save()
    # set staging type
    servers = Server.query.filter(Server.name.like('%Staging%')).all()
    for server in servers:
        server.type = Server.STAGING
        server.save()
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass