"""empty message

Revision ID: 8e2d9d09c0a
Revises: 194ec8738e52
Create Date: 2014-08-13 06:55:08.427180

"""

# revision identifiers, used by Alembic.
revision = '8e2d9d09c0a'
down_revision = '194ec8738e52'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('COMMIT')
    op.execute("ALTER TYPE xml_datasource_types ADD value 'input';")
    
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
