from api.accounts.views import *
from api.logs.views import *
from api.instances.views import *
from api.import_handlers.views import *
from api.ml_models.views import *
from api.model_tests.views import *
from api.features.views import *
from api.statistics.views import *
from api.reports.views import *
